name: Article Show Draft
on:
  pull_request_target:
    branches: ["main"]
    types: [labeled, opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  draft:
    uses: curvenote/actions/.github/workflows/draft.yml@v1
    with:
      venue: labs
      kind: article
      collection: blog
      path: blog/*
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
